using mockAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mockAPI
{
    public class Partner1DeductionInitializer
    {
        private Partner1DeductionContext _context;

        public Partner1DeductionInitializer(Partner1DeductionContext context)
        {
            _context = context;
        }

        public async Task Seed()
        {

            if (!_context.Partner1Deductions.Any())
            {
                _context.AddRange(Partner1Deductions);
                await _context.SaveChangesAsync();
            }
        }

        List<Partner1Deduction> Partner1Deductions = new List<Partner1Deduction>
        {
            new Partner1Deduction()
            {
                EmployeeId = "1",
                Agency = "agency1",
                AnnualMaximum = 1,
                CalcCode = "calcode1",
                CaseNo = "caseno1",
                CompanyNumber = "companynumber1",
                CostCenter1 = "costcenter11",
                CostCenter2 = "costcenter21",
                CostCenter3 = "costcenter31",
                Dcode = "1",
                EffectiveDate = "effectivedate1",
                EndDate = "enddate1",
                FipsCode = "fipscode1",
                Frequency = "frequency1",
                Goal = 1,
                IsSelfInsuredPlan = false,
                LoanFirstPaymentDate401K = "loanfirstpaymentdate401k1",
                LoanIssueDate401K = "loanissuedate401k1",
                LoadNumber = "loadnumber1",
                Maximum = 1,
                MedicalSupport = false,
                Minimum = 1,
                MiscInfo = "miscinfo1",
                PaidTowardsGoal = 1,
                Priority = "priority1",
                Rate = 1,
                ReportTerminated = true,
                SSN = "ssn1",
                StartDate = "startdate1",
                StateAbbrev = "stateabbrev1",
            },
                    new Partner1Deduction()
            {
                EmployeeId = "2",
                Agency = "agency2",
                AnnualMaximum = 2,
                CalcCode = "calcode2",
                CaseNo = "caseno2",
                CompanyNumber = "companynumber2",
                CostCenter1 = "costcenter12",
                CostCenter2 = "costcenter22",
                CostCenter3 = "costcenter32",
                Dcode = "2",
                EffectiveDate = "effectivedate2",
                EndDate = "enddate2",
                FipsCode = "fipscode2",
                Frequency = "frequency2",
                Goal = 2,
                IsSelfInsuredPlan = false,
                LoanFirstPaymentDate401K = "loanfirstpaymentdate401k2",
                LoanIssueDate401K = "loanissuedate401k2",
                LoadNumber = "loadnumber2",
                Maximum = 2,
                MedicalSupport = false,
                Minimum = 2,
                MiscInfo = "miscinfo2",
                PaidTowardsGoal = 2,
                Priority = "priority2",
                Rate = 2,
                ReportTerminated = true,
                SSN = "ssn2",
                StartDate = "startdate2",
                StateAbbrev = "stateabbrev2",
            },
                    new Partner1Deduction()
            {
                EmployeeId = "3",
                Agency = "agency3",
                AnnualMaximum = 3,
                CalcCode = "calcode3",
                CaseNo = "caseno3",
                CompanyNumber = "companynumber3",
                CostCenter1 = "costcenter13",
                CostCenter2 = "costcenter23",
                CostCenter3 = "costcenter33",
                Dcode = "3",
                EffectiveDate = "effectivedate3",
                EndDate = "enddate3",
                FipsCode = "fipscode3",
                Frequency = "frequency3",
                Goal = 3,
                IsSelfInsuredPlan = false,
                LoanFirstPaymentDate401K = "loanfirstpaymentdate401k3",
                LoanIssueDate401K = "loanissuedate401k3",
                LoadNumber = "loadnumber3",
                Maximum = 3,
                MedicalSupport = false,
                Minimum = 3,
                MiscInfo = "miscinfo3",
                PaidTowardsGoal = 3,
                Priority = "priority3",
                Rate = 3,
                ReportTerminated = true,
                SSN = "ssn3",
                StartDate = "startdate3",
                StateAbbrev = "stateabbrev3",
            },
            new Partner1Deduction()
            {
                EmployeeId = "4",
                Agency = "agency4",
                AnnualMaximum = 4,
                CalcCode = "calcode4",
                CaseNo = "caseno4",
                CompanyNumber = "companynumber4",
                CostCenter1 = "costcenter14",
                CostCenter2 = "costcenter24",
                CostCenter3 = "costcenter34",
                Dcode = "4",
                EffectiveDate = "effectivedate4",
                EndDate = "enddate4",
                FipsCode = "fipscode4",
                Frequency = "frequency4",
                Goal = 4,
                IsSelfInsuredPlan = false,
                LoanFirstPaymentDate401K = "loanfirstpaymentdate401k4",
                LoanIssueDate401K = "loanissuedate401k4",
                LoadNumber = "loadnumber4",
                Maximum = 4,
                MedicalSupport = false,
                Minimum = 4,
                MiscInfo = "miscinfo4",
                PaidTowardsGoal = 4,
                Priority = "priority4",
                Rate = 4,
                ReportTerminated = true,
                SSN = "ssn4",
                StartDate = "startdate4",
                StateAbbrev = "stateabbrev4",
            },
            new Partner1Deduction()
            {
                EmployeeId = "5",
                Agency = "agency5",
                AnnualMaximum = 5,
                CalcCode = "calcode5",
                CaseNo = "caseno5",
                CompanyNumber = "companynumber5",
                CostCenter1 = "costcenter15",
                CostCenter2 = "costcenter25",
                CostCenter3 = "costcenter35",
                Dcode = "5",
                EffectiveDate = "effectivedate5",
                EndDate = "enddate5",
                FipsCode = "fipscode5",
                Frequency = "frequency5",
                Goal = 4,
                IsSelfInsuredPlan = false,
                LoanFirstPaymentDate401K = "loanfirstpaymentdate401k5",
                LoanIssueDate401K = "loanissuedate401k5",
                LoadNumber = "loadnumber5",
                Maximum = 5,
                MedicalSupport = false,
                Minimum = 5,
                MiscInfo = "miscinfo5",
                PaidTowardsGoal = 5,
                Priority = "priority5",
                Rate = 5,
                ReportTerminated = true,
                SSN = "ssn5",
                StartDate = "startdate5",
                StateAbbrev = "stateabbrev5",
            },
            new Partner1Deduction()
            {
                EmployeeId = "6",
                Agency = "agency6",
                AnnualMaximum = 6,
                CalcCode = "calcode6",
                CaseNo = "caseno6",
                CompanyNumber = "companynumber6",
                CostCenter1 = "costcenter16",
                CostCenter2 = "costcenter26",
                CostCenter3 = "costcenter36",
                Dcode = "6",
                EffectiveDate = "effectivedate6",
                EndDate = "enddate6",
                FipsCode = "fipscode6",
                Frequency = "frequency6",
                Goal = 4,
                IsSelfInsuredPlan = false,
                LoanFirstPaymentDate401K = "loanfirstpaymentdate401k6",
                LoanIssueDate401K = "loanissuedate401k6",
                LoadNumber = "loadnumber6",
                Maximum = 6,
                MedicalSupport = false,
                Minimum = 6,
                MiscInfo = "miscinfo6",
                PaidTowardsGoal = 6,
                Priority = "priority6",
                Rate = 6,
                ReportTerminated = true,
                SSN = "ssn6",
                StartDate = "startdate6",
                StateAbbrev = "stateabbrev6",
            },

            new Partner1Deduction()
            {
                EmployeeId = "7",
                Agency = "agency7",
                AnnualMaximum = 7,
                CalcCode = "calcode7",
                CaseNo = "caseno7",
                CompanyNumber = "companynumber7",
                CostCenter1 = "costcenter17",
                CostCenter2 = "costcenter27",
                CostCenter3 = "costcenter37",
                Dcode = "7",
                EffectiveDate = "effectivedate7",
                EndDate = "enddate7",
                FipsCode = "fipscode7",
                Frequency = "frequency7",
                Goal = 4,
                IsSelfInsuredPlan = false,
                LoanFirstPaymentDate401K = "loanfirstpaymentdate401k7",
                LoanIssueDate401K = "loanissuedate401k7",
                LoadNumber = "loadnumber7",
                Maximum = 7,
                MedicalSupport = false,
                Minimum = 7,
                MiscInfo = "miscinfo7",
                PaidTowardsGoal = 7,
                Priority = "priority7",
                Rate = 7,
                ReportTerminated = true,
                SSN = "ssn7",
                StartDate = "startdate7",
                StateAbbrev = "stateabbrev7",
            },
        };
    }
}